name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 * * * *'
    workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: sarisia/actions-readme-feed@v1
            with:
              url: 'alishahidinet.ir/feed'
              file: 'README.md'
          - uses: sarisia/actions-commit@master
